# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml

analyzer:
  exclude:
    - '**/*.g.dart'   # generated files
    - '**/*.freezed.dart'
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    # Dart 3 style
    - prefer_final_locals
    - prefer_final_in_for_each
    - unnecessary_nullable_for_final_variable_declarations
    - use_super_parameters

    # Safety
    - avoid_dynamic_calls
    - avoid_print             # use a logger in production
    - cancel_subscriptions
    - close_sinks

    # Collections
    - prefer_collection_literals
    - prefer_spread_collections

    # Async
    - unawaited_futures
    - avoid_void_async